function Print-Info($m){Write-Host "[INFO] $m" -ForegroundColor Blue}
function Print-Success($m){Write-Host "[SUCCESS] $m" -ForegroundColor Green}
function Print-Warning($m){Write-Host "[WARNING] $m" -ForegroundColor Yellow}
function Print-Error($m){Write-Host "[ERROR] $m" -ForegroundColor Red}
function Detect-ComposeCmd{try{docker compose version *> $null;$script:COMPOSE_CMD="docker compose"}catch{if(Get-Command docker-compose -ErrorAction SilentlyContinue){$script:COMPOSE_CMD="docker-compose"}else{throw "Docker Compose 未安装"}};Print-Info "使用 Docker Compose 命令: $COMPOSE_CMD"}
function Check-Docker{if(-not (Get-Command docker -ErrorAction SilentlyContinue)){throw "Docker 未安装"};Detect-ComposeCmd;Print-Success "Docker 和 Docker Compose 已安装"}
function Check-Env{if(-not (Test-Path ".env")){Print-Warning ".env 不存在，从模板复制";Copy-Item ".env.example" ".env";Print-Info "已使用默认环境变量创建 .env"};Print-Success "环境变量文件存在"}
function Ensure-Config{if(-not (Test-Path "config.json")){Print-Warning "config.json 不存在，从模板复制";Copy-Item "config.json.example" "config.json";Print-Info "已使用默认配置创建 config.json"};Print-Success "配置文件存在"}
function Read-EnvVars{$front=3000;$back=8080;if(Test-Path ".env"){Get-Content ".env"|ForEach-Object{if($_ -match '^NOFX_FRONTEND_PORT=(.+)$'){$front=$matches[1].Trim()}elseif($_ -match '^NOFX_BACKEND_PORT=(.+)$'){$back=$matches[1].Trim()}}};$script:NOFX_FRONTEND_PORT=$front;$script:NOFX_BACKEND_PORT=$back}
function Generate-JwtSecret{$b=New-Object byte[] 48;[System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b);[Convert]::ToBase64String($b)}
function Ensure-JwtSecretInConfig{if(-not (Test-Path "config.json")){return};$json=Get-Content "config.json" -Raw|ConvertFrom-Json;$def="";if(Test-Path "config.json.example"){try{$def=(Get-Content "config.json.example" -Raw|ConvertFrom-Json).jwt_secret}catch{}};if([string]::IsNullOrWhiteSpace($json.jwt_secret) -or ($def -and $json.jwt_secret -eq $def)){$s=Generate-JwtSecret;$json.jwt_secret=$s;$json|ConvertTo-Json -Depth 10|Set-Content "config.json" -Encoding utf8;Print-Success "已生成并写入 jwt_secret"}}
function Sync-EnvJwtSecret{if(-not (Test-Path "config.json")){return};$j=Get-Content "config.json" -Raw|ConvertFrom-Json;$s=[string]$j.jwt_secret;if([string]::IsNullOrWhiteSpace($s)){return};if(Test-Path ".env"){if((Get-Content ".env") -match '^JWT_SECRET='){((Get-Content ".env") -replace '^JWT_SECRET=.*$',"JWT_SECRET=$s")|Set-Content ".env" -Encoding utf8}else{Add-Content ".env" "`nJWT_SECRET=$s"};Print-Success "已同步 .env 中的 JWT_SECRET"}}
function Detect-Hardware{$script:CPU_CORES=[Environment]::ProcessorCount;$mem=(Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory;$script:TOTAL_MEM_GB=[int]([math]::Floor($mem/1GB));if($CPU_CORES -lt 1){$CPU_CORES=1};if($TOTAL_MEM_GB -lt 1){$TOTAL_MEM_GB=1}}
function Apply-Resource-Limits{Detect-Hardware;$backend=1;$frontend=0.5;if($CPU_CORES -ge 8){$backend=4}elseif($CPU_CORES -ge 4){$backend=3}elseif($CPU_CORES -ge 2){$backend=1.5};$half=[int]([math]::Floor($TOTAL_MEM_GB/2));$bm="1g";if($half -gt 8){$bm="8g"}elseif($half -ge 1){$bm="$half"+"g"};$fm="256m";if(docker ps --format '{{.Names}}'|Select-String '^nofx-trading$'){docker update --cpus $backend --memory $bm nofx-trading *> $null};if(docker ps --format '{{.Names}}'|Select-String '^nofx-frontend$'){docker update --cpus $frontend --memory $fm nofx-frontend *> $null};Print-Info "已根据硬件参数应用资源限额"}
function Start-Compose($opt){Print-Info "正在启动 NOFX AI Trading System";Read-EnvVars;if(-not (Test-Path "config.db")){New-Item -ItemType File -Path "config.db" *> $null};if(-not (Test-Path "decision_logs")){New-Item -ItemType Directory -Path "decision_logs" *> $null};if($opt -eq "--build"){Print-Info "重新构建镜像";& $COMPOSE_CMD up -d --build}else{Print-Info "启动容器";& $COMPOSE_CMD up -d};Apply-Resource-Limits;Print-Success "服务已启动";Print-Info "Web 界面: http://localhost:$NOFX_FRONTEND_PORT";Print-Info "API 端点: http://localhost:$NOFX_BACKEND_PORT"}
function Stop-Compose{Print-Info "正在停止服务";& $COMPOSE_CMD stop;Print-Success "服务已停止"}
function Restart-Compose{Print-Info "正在重启服务";& $COMPOSE_CMD restart;Print-Success "服务已重启"}
function Logs($svc){if([string]::IsNullOrWhiteSpace($svc)){& $COMPOSE_CMD logs -f}else{& $COMPOSE_CMD logs -f $svc}}
function Status{Read-EnvVars;Print-Info "服务状态";& $COMPOSE_CMD ps;Print-Info "健康检查";try{(Invoke-WebRequest -Uri "http://localhost:$NOFX_BACKEND_PORT/api/health" -UseBasicParsing).Content|Write-Host}catch{Write-Host "后端未响应"}}
function Clean{Print-Warning "这将删除所有容器和数据";$c=Read-Host "确认删除？(yes/no)";if($c -eq "yes"){Print-Info "正在清理";& $COMPOSE_CMD down -v;Print-Success "清理完成"}else{Print-Info "已取消"}}
function Update{Print-Info "正在更新";git pull;& $COMPOSE_CMD up -d --build;Print-Success "更新完成"}
param($Command,$Option)
try{Check-Docker;switch($Command){"stop"{Stop-Compose};"restart"{Restart-Compose};"logs"{Logs $Option};"status"{Status};"clean"{Clean};"update"{Update};default{Check-Env;Ensure-Config;Ensure-JwtSecretInConfig;Sync-EnvJwtSecret;Start-Compose $Option}}}catch{Print-Error $_.Exception.Message;exit 1}